server:
  port: 0
  display-name: Consumer
eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    hostname: 127.0.0.1
  client:
      serviceUrl:
        defaultZone: http://127.0.0.1:8070/eureka/
spring:
  application:
    name: Consumer