server:
  port: 0
  display-name: Producer

eureka:
  client:
    serviceUrl:
          defaultZone: http://127.0.0.1:8070/eureka/

  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}:1.0.2
    hostname: 127.0.0.1
    metadata-map:
      version: 1.0.0

spring:
  application:
    name: Producer
